spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vidhyalaya17@gmail.com
    password: V1i9j8i5 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
eureka:
  client:
    register-with-eureka: true
    eureka-server-port: 8761
