spring:
 data:
  mongodb:
   uri: mongodb+srv://admin:femLZHkRKLMzfQcP@vidh-cls.zuk8k.mongodb.net/ividhyalaya?retryWrites=true&w=majority
server:
 port: 8081
vidhyalaya:
 email:
  subject: Registration email -
  body: <html></html>
